### ISSUE TITLE
better Viewstate implementation

### ISSUE THREAD

**Issue by philippdormann** [philippdormann/gymhmensa#10]
see #9

**Comment by DATBOIWASHERE** [comment]
Biete Hilfe an, warte auf Erlaubnis zur Mitarbeit @philippdormann

**Comment by philippdormann** [comment]
Kannst gerne das Projekt forken und am [Parser](https://github.com/philippdormann/gymhmensa/blob/dev/api/parser.js) bauen.
Die JSON Outputs passen momentan noch nicht ganz, z.B. werden leere Elemente aktuell einfach übersprungen (Mensamax Markup ist relativ defekt/ komplex zu parsen)

Beispiel:
![image](https://user-images.githubusercontent.com/17651032/123419327-63cdd800-d5ba-11eb-96d5-3c45c1b92411.png)

**Comment by Mic-Rei** [comment]
Habe eine Mögliche Lösung
Wird dir Wahrscheinlich nicht gefallen, trotzdem hören?

**Comment by Mic-Rei** [comment]
> Habe eine Mögliche Lösung
> Wird dir Wahrscheinlich nicht gefallen, trotzdem hören?

Ich würde Vorschlagen, das Projekt nochmal neu anzugehen und in Phyton zu schreiben, hier wäre es einfacher möglich, die Website durchsuchen zu lassen und nur die benötigten werte dynamisch in eine Datei umwandeln zu lassen,, die dann auf einem Server liegt, der diese dann verteilt. Hier würden leere Objekte dann trotzdem beachtet werden.

**Comment by Mic-Rei** [comment]
> > Habe eine Mögliche Lösung
> > Wird dir Wahrscheinlich nicht gefallen, trotzdem hören?
> 
> Ich würde Vorschlagen, das Projekt nochmal neu anzugehen und in Phyton zu schreiben, hier wäre es einfacher möglich, die Website durchsuchen zu lassen und nur die benötigten werte dynamisch in eine Datei umwandeln zu lassen,, die dann auf einem Server liegt, der diese dann verteilt. Hier würden leere Objekte dann trotzdem beachtet werden.

Javascript wird immer seine Probleme haben

**Comment by Mic-Rei** [comment]
Oder

**Comment by Mic-Rei** [comment]
Viel Einfacher

**Comment by Mic-Rei** [comment]
Die Website einfach als iFrame einbetten als Übergangslösung ;)

**Comment by Mic-Rei** [comment]
> Die Website einfach als iFrame einbetten als Übergangslösung ;)

Bitte um Antwort

**Comment by nicolaiort** [comment]
GitHub ist kein Chat.
Danke für deinen Input, du kannst gerne das Projekt forken, wie @philippdormann geschrieben hat und die Python Sache bauen :)

**Comment by Mic-Rei** [comment]
> GitHub ist kein Chat.
> Danke für deinen Input, du kannst gerne das Projekt forken, wie @philippdormann geschrieben hat und die Python Sache bauen :)

Tschuldigung, bin ein anderes Programm gewöhn, dass mehr als Chat arbeitet...

**Comment by Mic-Rei** [comment]
habe ein Problem, bitte um Hilfe:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\michi\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\michi\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\michi\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\michi\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\michi\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\michi\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by nicolaiort** [comment]
Implemented via new parser by @philippdormann (still in js :P)
