### ISSUE TITLE
Alternative fetcher using selenium

### ISSUE THREAD

**Issue by JumpLink** [philippdormann/gymhmensa#12]
hi,
I tried to use your scraper for [our current project](https://github.com/ArtCodeStudio/gymnasium-otterndorf-website), but it didn't work well for us. So we wrote our own little scraper which I want to show you here, because it might be helpful for this project.

Everything you need for this is defined in our [mensa-max.service.ts](https://github.com/ArtCodeStudio/gymnasium-otterndorf-website/blob/main/app/nest/src/api/mensa-max/mensa-max.service.ts).

Instead of using npm request, fetch or similar we use Selenium with Firefox (in headless mode) because we had difficulties to get the session cookie. Selenium is normally used of for E2E testing and possibly an overloaded solution, but the advantage is that this should now make it very difficult for MensaMax to break this, as we query the data with a real browser and then simply read out the html (this solution will also run MensaMax's JavaScript in the browser) and then process the html with cheerio like you. 

I hope this can be helpful

**Comment by philippdormann** [comment]
Hi Pascal,

thanks for your input and the effort.
The goal of this project was to keep it lightweight, so Selenium/ Playwright/ Puppeteer don't really fit in.

I have not worked on this project in quite some time, so this has been broken for a bit.

Recently found a better implementation for bypassing the viewstate/ accessing the html content. Will push an update to the main branch soon 🧐

In the meantime, feel free to take a look @ the `dev` branch 🤓
